import './assets/style.css';

export const metadata = {
    title: 'Gestion de clientes',
    description: "Generated by create next app",
   
};


export default function Layout({ children }) {
    return (
        <main className='__width-complete __padding1rem __padding-button flex columns __oneGap' style={{height: '100%'}}>
            { children }
        </main>
    );
}