
export const metadata = {
    title: 'Gestion de clientes',
    description: "Generated by create next app",

};


export default function Layout({ children }) {
    return (
        <section className='w-full h-full flex gap-[.5rem]'>
            {children}
        </section>
    );
}