import '../../style/Lobby.css';
import '../../style/style.css';
import '../../style/formCorte.css';

import Header from '@/components/Header/Header';


export const metadata = {
    title: "Corte365 ",
    description: "Generated by create next app",
};


export default function CorteLayout({ children }) {
    return (
        <>{ children }</>
    );
}
