

export const metadata = {
    title: 'Gestion de alertas',
    description: "Generated by create next app",
   
};


export default function Layout({ children }) {
    return (
        <>
            { children }
        </>
    );
}