import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export const metadata = {
    title: "Muro de novedades",
    description: "Generated by create next app",
   
};


export default function LobbyLayout({ children }) {
    return (
        <>{ children }</>
    );
}